using System;
using System.Collections.Generic;
using System.Linq;

namespace EulerProblems {
	public static class Program {

		// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

		// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

		public static int[] Fibonacci(int max) {
			var numbers = new List<int>();

			int fib = 0;
			int fib2 = 1;


			while(fib <= max) {
				numbers.Add(fib);

				int tmp = fib2;
				fib2 += fib;
				fib = tmp;
			}

			return numbers.ToArray();
		}

		public static void Main() {
			Console.WriteLine(Fibonacci(4000000).Where(i => i % 2 == 0).Sum());
			Console.ReadLine();
		}
	}
}
